<div class="reg d-sm-block w-100 border pb-3 mb-3 bg-white">
    <h1 class="p-md-3">Uživatelé</h1>
    <table class="table table-bordered table-striped table-hover">
        <thead class="bg-primary">
        <td>Jméno</td>
        <td>Email</td>
        <td>Adresa</td>
        <td>Profil uživatele</td>
        </thead>
        <?php foreach ($uzivatele as $uzivatel) : ?>
            <tr>
                <td>
                    <?= $uzivatel['jmeno'] . " " . $uzivatel['prijmeni'] ?>
                </td>
                <td>
                    <?= $uzivatel['email'] ?>
                </td>
                <td>
                    <?= $uzivatel['adresa'] . ", " . $uzivatel['mesto'] . ", " . $uzivatel['psc'] ?>
                </td>
                <td>
                    <a class="btn-sm btn-primary text-decoration-none" href="admin-profil?id=<?= $uzivatel['uzivatel_id'] ?>" role="button">Info</a>
                    <?php if ($uzivatel['admin']) : ?>
                        <a class="btn-sm btn-danger invisible" onclick="return confirm('Smazat uživatele?')"
                           href="admin-uzivatele?id=<?= $uzivatel['uzivatel_id'] ?>" role="button">Smazat</a>
                    <?php else : ?>
                        <a class="btn-sm btn-danger text-decoration-none" onclick="return confirm('Smazat uživatele<?= " " . $uzivatel['jmeno'] . " " . $uzivatel['prijmeni'] ?>?')"
                           href="admin-uzivatele?id=<?= $uzivatel['uzivatel_id'] ?>" role="button">Smazat</a>
                    <?php endif ?>
                </td>
            </tr>
        <?php endforeach ?>
    </table>
</div>