<div class="reg d-sm-block w-100 border pb-3 mb-3 bg-white">
    <div class="p-5 accordion offset-3 w-50" id="accordionExample">
        <div class="harmonika border-bottom">
            <h2 class="accordion-header" id="hlavickaZivot">
                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                        data-bs-target="#podrobnostiZivot" aria-expanded="false" aria-controls="podrobnostiZivot">
                    Životní pojištění
                </button>
            </h2>
            <div id="podrobnostiZivot" class="accordion-collapse collapse" aria-labelledby="hlavickaZivot"
                 data-bs-parent="#accordionExample">
                <div class="accordion-body">
                    Životní pojištění chrání vás i vaši rodinu před finančními dopady nenadálých životních situací. Se
                    správně nastaveným pojištěním budete kryti před <strong>riziky ohrožující zdraví i život</strong>.


                </div>
            </div>
        </div>
        <div class="harmonika border-bottom">
            <h2 class="accordion-header" id="hlavickaUraz">
                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                        data-bs-target="#podrobnostiUraz" aria-expanded="false" aria-controls="podrobnostiUraz">
                    Úrazové pojištění
                </button>
            </h2>
            <div id="podrobnostiUraz" class="accordion-collapse collapse" aria-labelledby="hlavickaUraz"
                 data-bs-parent="#accordionExample">
                <div class="accordion-body">
                    Úraz se může stát každému z nás nejen při sportu, ale i doma, stačí chvilka nepozornosti. U lehkého
                    úrazu vás nebude jeho léčení omezovat a můžete i pracovat. Když půjde o závažnější úraz, budete
                    hospitalizováni, pak budou následovat rehabilitace. Nebudete moci chodit do práce a tím dojde k
                    výpadku
                    vašeho příjmu. Úrazové pojištění pomůže při poškození vašeho zdraví z vnějších příčin. <strong>Nekryje
                        případy
                        kdy, si poškození způsobíte sami</strong>.
                </div>
            </div>
        </div>
        <div class="harmonika border-bottom">
            <h2 class="accordion-header" id="hlavickaDomacnost">
                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                        data-bs-target="#podrobnostiDomacnost" aria-expanded="false"
                        aria-controls="podrobnostiDomacnost">
                    Pojištění domácnosti
                </button>
            </h2>
            <div id="podrobnostiDomacnost" class="accordion-collapse collapse" aria-labelledby="hlavickaDomacnost"
                 data-bs-parent="#accordionExample">
                <div class="accordion-body">
                    Když vás vykradou nebo věci ve vaší domácnosti poškodí přírodní živly, vyplatíme vám peníze, za
                    které si
                    snadno obstaráte nové vybavení domácnosti. Pojistíme vám i věci uschované mimo vaši domácnost, např.
                    v
                    kočárkárně, sklepě, ale i například věci ve skříňce ve fitku. Pojištěné máte i osobní věci, včetně
                    oblečení, elektroniky nebo sportovních potřeb. Dále se pojištění vztahuje i na odcizení uzamčeného
                    kola.
                </div>
            </div>
        </div>
        <div class="harmonika">
            <h2 class="accordion-header" id="hlavickaCesta">
                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                        data-bs-target="#podrobnostiCesta" aria-expanded="false" aria-controls="podrobnostiCesta">
                    Cestovní pojištění
                </button>
            </h2>
            <div id="podrobnostiCesta" class="accordion-collapse collapse" aria-labelledby="hlavickaCesta"
                 data-bs-parent="#accordionExample">
                <div class="accordion-body">
                    Pokud vyrážíte na cesty, je dobré si sjednat krátkodobé <strong>pojištění úrazu v rámci cestovního
                        pojištění</strong> pro
                    termín cesty.
                </div>
            </div>
        </div>
        <a class="btn btn-primary d-flex justify-content-center" href="registrace" role="button">Sjednat pojištění</a>
    </div>
</div>