<div class="reg d-sm-block w-100 border pb-3 mb-3 bg-white">
    <br/>
    <h1 class="text-primary">Přihlášení</h1>
    <br/>
    <div class="container">
        <form method="post">
            <div class="m-3 d-flex justify-content-center">
                <div class="form-group col-lg-4">
                    <label for="prihlaseni-email">E-mail</label>
                    <input type="email" name="email" class="form-control" id="prihlaseni-email"
                           aria-describedby="popisEmailu"
                           placeholder="E-mail">
                </div>

            </div>
            <div class="d-flex justify-content-center">
                <div class="form-group col-lg-4">
                    <label for="prihlaseni-heslo">Heslo</label>
                    <input type="password" name="heslo" class="form-control" id="prihlaseni-heslo"
                           placeholder="Zadej heslo ">
                </div>
            </div>
            <br/>
            <button type="submit" class="btn btn-primary">Přihlásit</button>
        </form>
        <br/>
        <p>Pokud ještě nemáte účet, <a href="registrace">zaregistrujte se</a>.</p>

        <br/>
    </div>

</div>
