<div class="reg d-sm-block w-100 border pb-3 mb-3 bg-white">
    <br/>
    <h1 class="text-primary">Registrace</h1>
    <br/>
    <div class="container">
        <form method="post">
            <div class="d-flex justify-content-center">
                <div class="form-row">
                    <div class="form-group col-lg-10">
                        <label for="prihlaseni-jmeno">Jméno</label>
                        <input type="text" name="jmeno" class="form-control" id="prihlaseni-jmeno" placeholder="Jméno">
                    </div>
                </div>
                <div class="d-flex justify-content-center">
                    <div class="form-group col-lg-10">
                        <label for="prihlaseni-prijmeni">Příjmení</label>
                        <input type="text" name="prijmeni" class="form-control" id="prihlaseni-prijmeni" placeholder="Příjmení">
                    </div>
                </div>
                <div class="d-flex justify-content-center">
                    <div class="form-group col-lg-10">
                        <label for="prihlaseni-email">E-mail</label>
                        <input type="text" name="email" class="form-control" id="prihlaseni-email" placeholder="E-mail">
                    </div>
                </div>
            </div>
            <br/>
            <div class="d-flex justify-content-center">
                <div class="form-row">
                    <div class="form-group col-lg-10">
                        <label for="prihlaseni-adresa">Adresa</label>
                        <input type="text" name="adresa" class="form-control" id="prihlaseni-adresa"
                               placeholder="Adresa">
                    </div>
                </div>

                <div class="d-flex justify-content-center">
                    <div class="form-group col-lg-10">
                        <label for="prihlaseni-mesto">Město</label>
                        <input type="text" name="mesto" class="form-control" id="prihlaseni-mesto" placeholder="Město">
                    </div>
                </div>

                <div class="d-flex justify-content-center">
                    <div class="form-group col-lg-10">
                        <label for="prihlaseni-psc">PSČ</label>
                        <input type="text" name="psc" class="form-control" id="prihlaseni-psc" placeholder="PSC">
                    </div>
                </div>
            </div>
            <br/>
            <div class="d-flex justify-content-center">
                <div class="form-row">
                    <div class="form-group col-lg-10">
                        <label for="prihlaseni-heslo">Heslo</label>
                        <input type="password" name="heslo" class="form-control" id="prihlaseni-heslo"
                               placeholder="Zadej heslo ">
                    </div>
                </div>

                <div class="d-flex justify-content-center">
                    <div class="form-group col-lg-10">
                        <label for="prihlaseni-heslo">Heslo znovu</label>
                        <input type="password" name="heslo_znovu" class="form-control" id="prihlaseni-heslo"
                               placeholder="Stejné heslo ">
                    </div>
                </div>

                <div class="d-flex justify-content-center">
                    <div class="form-group col-lg-10">
                        <label for="prihlaseni-antispam">Antispam</label>
                        <input type="text" name="rok" class="form-control" id="prihlaseni-antispam"
                               placeholder="Aktuální rok">
                    </div>
                </div>
            </div>
            <br/>
            <button type="submit" class="btn btn-primary">Registrovat</button>
        </form>

    </div>

</div>
