<!DOCTYPE html>
<html lang="cs-cz">

<head>
    <base href="/localhost"/>
    <meta charset="UTF-8"/>
    <title><?= $titulek ?></title>
    <meta name="description" content="<?= $popis ?>"/>
    <meta name="keywords" content="<?= $klicova_slova ?>"/>
    <link rel="stylesheet" href="/css/bootstrap.min.css" type="text/css"/>
    <link rel="stylesheet" href="../css/style.css" type="text/css"/>
    <script src="/js/bootstrap.bundle.min.js"></script>
    <script src="https://kit.fontawesome.com/12c379091f.js" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-alpha3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js"></script>
</head>

<body class="bg-light">
<div class="nav">
    <div class="container">
        <header
                class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">
            <a href="/" class="d-flex align-items-center col-md-3 mb-2 mb-md-0 text-decoration-none">
            </a>


            <ul class="nav col-auto col-md-auto mb-2 justify-content-center mb-md-0">
                <li><a href="uvod"id="navigace"class="nav-link px-2">Úvod</a></li>
                <li><a href="prehled-pojisteni" id="navigace"class="nav-link px-2">Pojištění</a></li>
            </ul>

            <div class="col-lg-3 text-end">
                <a href="prihlaseni">
                <button type="button" class="btn btn-outline-primary me-2">Přihlásit</button></a>
                <a href="registrace">
                    <button type="button" class="btn btn-primary">Registrovat</button>
</a>
            </div>
        </header>
    </div>
</div>

    <div class="b-example-divider"></div>
<main class="container">
<?php foreach ($zpravy as $zprava) : ?>
    <p class="zprava"><?= $zprava ?></p>
<?php endforeach ?>
<article>
    <?php $this->kontroler->vypisPohled(); // vložení aktuálního pohledu do šablony
    ?>
</article>
</main>
<div class="container">
    <footer class="py-3 my-4">
        <ul class="nav justify-content-center border-bottom pb-3 mb-3">

        </ul>
        <p class="text-center text-muted">&copy; 2023 Tomáš Kuruc</p>
    </footer>
</div>
</body>

</html>