<!DOCTYPE html>
<html lang="cs-cz">

<head>
    <base href="/localhost"/>
    <meta charset="UTF-8"/>
    <title><?= $titulek ?></title>
    <meta name="description" content="<?= $popis ?>"/>
    <meta name="keywords" content="<?= $klicova_slova ?>"/>
    <link rel="stylesheet" href="/css/bootstrap.min.css" type="text/css"/>
    <link rel="stylesheet" href="../css/style.css" type="text/css"/>
    <script src="/js/bootstrap.bundle.min.js"></script>
    <script src="https://kit.fontawesome.com/12c379091f.js" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-alpha3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js"></script>
</head>

<body class="bg-light">
<div class="nav ">
    <div class="container">
        <header class="d-flex bg-light flex-wrap align-items-center justify-content-center justify-content-md-between py-2 mb-2 border-bottom">

            <?php if ($admin) : ?>

                <div class="d-flex align-items-center col-md-4 mb-2 mb-md-0">
                    <a href="administrace">
                        <button type="button" class="btn btn-sm btn-outline-danger">Administrace</button>
                    </a>
                </div>
            <?php else: ?>
                <div class="d-flex align-items-center col-md-4 mb-2 mb-md-0">
                    <a href="administrace">
                        <button type="button" class="btn btn-sm btn-outline-primary">Administrace</button>
                    </a>
                </div>
            <?php endif ?>

            <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
                <li><a href="uvod"id="navigace"class="nav-link px-2">Úvod</a></li>
                <li><a href="prehled-pojisteni" id="navigace"class="nav-link px-2">Pojištění</a></li>
            </ul>

            <div class=" offset-md-2 col-md-2 text-end dropdown">

                <button class="btn btn-outline-primary d-block text-decoration-none dropdown-toggle"
                        data-bs-toggle="dropdown" aria-expanded="false">
                    <?= $uzivatel['email']; ?>
                </button>
                <ul class="dropdown-menu text-small shadow">
                    <li><a class="dropdown-item" href="sjednat-pojisteni">Nové pojištění</a></li>
                    <li><a class="dropdown-item" href="profil">Profil</a></li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>
                    <li><a class="dropdown-item" href="administrace/odhlasit">Odhlásit</a></li>
                </ul>
            </div>
        </header>
    </div>
</div>

<main class="container">

    <article>
        <?php foreach ($zpravy as $zprava) : ?>
            <p class="zprava"><?= $zprava ?></p>
        <?php endforeach ?>

        <?php $this->kontroler->vypisPohled(); // vložení aktuálního pohledu do šablony
        ?>
    </article>
</main>

<div class="container">
    <footer class="py-3 my-2">
        <div class="nav justify-content-center border-bottom pb-3 mb-3">

        </div>
        <p class="text-center text-muted">&copy; 2023 Tomáš Kuruc</p>
    </footer>
</div>
</body>

</html>