<div class="reg d-sm-block w-100 border pb-3 mb-3 bg-white">
    <br/>
    <div>
        <h2 class="text-primary">Pojistovna</h2>
        <br/>
        <p class="m-3">Lorem ipsum dolor sit amet, consectetur adipisicing elit. A consequuntur cupiditate dolore excepturi id, nisi numquam officia quo tempora tenetur. Accusantium cumque eaque exercitationem illum minus quia sed tempora voluptatum!</p>
        <br/>
        <p class="m-3">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid aperiam, atque consequuntur deleniti distinctio doloremque et impedit iste mollitia nulla pariatur placeat quia quibusdam, reprehenderit sapiente sed sequi tempore, veritatis.</p>
        <br/>
        <a class="btn btn-outline-primary" href="prehled-pojisteni" role="button">Přehled pojištění</a>
        <br/>
    </div>
</div>
